### ISSUE TITLE
Spatial Correlations

### ISSUE THREAD

**Issue by dsigler1234** [mape-maker/mape-maker#41]
Hello,

I was wondering if an energy system has more than one wind site does this repo have the capability to create spatially correlated scenarios for more than one site, assuming forecasts and actuals are known for both sites. 

I understand I could create scenarios separately for two different wind sites using forecasts and actuals, however if there are correlations between the two sites it would be nice to capture that.

Best,

Devon

**Comment by DLWoodruff** [comment]
We did some work on that a few years ago, but didn’t get it done. I’ll see
if I can find any code.

Shorter answer: no, the software doesn’t have capability
